apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-handler
  namespace: mongo
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx: localhost/k8s-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-handler
  template:
    metadata:
      labels:
        app: mongo-handler
    spec:
      serviceAccountName: mongo
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mongo-handler
        image: mongo-handler
        args:
        - --port
        - "9539"
        - --connection-str
        - mongodb://mongo-db-svc:9374
        imagePullPolicy: IfNotPresent
        startupProbe:
          httpGet:
            path: /ready
            port: 9539
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9539
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /alive
            port: 9539
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 10001
          runAsGroup: 20001
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['ALL']
          runAsNonRoot: true
          readOnlyRootFilesystem: true
