apiVersion: batch/v1
kind: Job
metadata:
  name: test-find-by-id
  namespace: mongo
spec:
  activeDeadlineSeconds: 900
  template:
    spec:
      serviceAccountName: mongo
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: test-find-by-id
        image: curl
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - |
          curl -X POST http://mongo-handler-svc:9539/findById \
          -H 'Content-Type: application/json' \
          -d '{"Id":"a12345"}'
        securityContext:
          runAsUser: 10001
          runAsGroup: 20001
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
      restartPolicy: Never
