apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  namespace: mongo
spec:
  selector:
    app: mongo-db
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9374
    targetPort: 27017
    nodePort: 32000